import { z } from 'zod';

export const devoteeSchema = z.object({
  id: z.number().int(),
  leader_id: z.number().int().nullable().optional(),
  system_role_id: z.number().int().nullable().optional(),
  status: z.enum(['active', 'inactive', 'deceased']).optional(),
  name: z.string().max(100).optional(),
  initiated_name: z.string().max(100).nullable().optional(),
  dob: z.date().nullable().optional(),
  whatsapp_consent: z.boolean().optional(),
  phone_whatsapp: z.string().max(21).nullable().optional(),
  email: z.string().regex(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i, 'Invalid Email').max(255).nullable().optional(),
  email_verified: z.boolean().optional(),
  gender: z.enum(['male', 'female', 'other']).nullable().optional(),
  occupation: z.string().max(21).nullable().optional(),
  occupation_position: z.string().max(100).nullable().optional(),
  tax_80g_required: z.boolean().optional(),
  tax_pan: z.string().max(10).nullable().optional(),
  skills: z.any().nullable().optional(),
  temple_memberships: z.any().nullable().optional(),
  class_memberships: z.any().nullable().optional(),
  address_line1: z.string().max(255).nullable().optional(),
  address_line2: z.string().max(255).nullable().optional(),
  address_society: z.string().max(255).nullable().optional(),
  address_area: z.string().max(255).nullable().optional(),
  address_gmap_url: z.string().nullable().optional(),
  address_city: z.string().max(100).nullable().optional(),
  address_state: z.string().max(100).nullable().optional(),
  address_pincode: z.string().max(20).nullable().optional(),
  address_country: z.string().max(100).nullable().optional(),
  language_preference: z.string().max(21).nullable().optional(),
  marital_status: z.boolean().optional(),
  spouse_name: z.string().max(100).nullable().optional(),
  spouse_dob: z.date().nullable().optional(),
  spouse_marriage_anniversary: z.date().nullable().optional(),
  parents_father_name: z.string().max(100).nullable().optional(),
  parents_father_dob: z.date().nullable().optional(),
  parents_mother_name: z.string().max(100).nullable().optional(),
  parents_mother_dob: z.date().nullable().optional(),
  parents_marriage_anniversary: z.date().nullable().optional(),
  children_1_name: z.string().max(100).nullable().optional(),
  children_1_dob: z.date().nullable().optional(),
  children_2_name: z.string().max(100).nullable().optional(),
  children_2_dob: z.date().nullable().optional(),
  children_3_name: z.string().max(100).nullable().optional(),
  children_3_dob: z.date().nullable().optional(),
  children_4_name: z.string().max(100).nullable().optional(),
  children_4_dob: z.date().nullable().optional(),
});