import { z } from 'zod';

export const devoteeSchema = z.object({
  id: z.number().int(),
  name: z.string().max(100),
  initiated_name: z.string().max(100).nullable(),
  dob: z.date().nullable(),
  whatsapp_consent: z.boolean(),
  phone_whatsapp: z.string().max(21).nullable(),
  email: z.string().regex(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i, 'Invalid Email').max(255).nullable(),
  email_verified: z.boolean(),
  role_id: z.number().int(),
  gender: z.enum(['male', 'female', 'other']).nullable(),
  occupation: z.string().max(21).nullable(),
  occupation_position: z.string().max(51).nullable(),
  skills: z.any().nullable(),
  temple_memberships: z.any().nullable(),
  class_memberships: z.any().nullable(),
  address_line1: z.string().max(255).nullable(),
  address_line2: z.string().max(255).nullable(),
  address_society: z.string().max(255).nullable(),
  address_area: z.string().max(255).nullable(),
  address_gmap_url: z.string().nullable(),
  address_city: z.string().max(100).nullable(),
  address_state: z.string().max(100).nullable(),
  address_pincode: z.string().max(6).nullable(),
  address_country: z.string().max(100).nullable(),
  language_preference: z.string().max(21).nullable(),
  marital_status: z.boolean(),
  spouse_name: z.string().max(100).nullable(),
  spouse_dob: z.date().nullable(),
  spouse_marriage_anniversary: z.date().nullable(),
  parents_father_name: z.string().max(100).nullable(),
  parents_father_dob: z.date().nullable(),
  parents_mother_name: z.string().max(100).nullable(),
  parents_mother_dob: z.date().nullable(),
  parents_marriage_anniversary: z.date().nullable(),
  children_1_name: z.string().max(100).nullable(),
  children_1_dob: z.date().nullable(),
  children_2_name: z.string().max(100).nullable(),
  children_2_dob: z.date().nullable(),
  children_3_name: z.string().max(100).nullable(),
  children_3_dob: z.date().nullable(),
  children_4_name: z.string().max(100).nullable(),
  children_4_dob: z.date().nullable(),
});